name: run tests.js
on: [push, pull_request]

jobs:
  test:
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'
    - run: npm install
    - run: node tests.js
